---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
big_sphere <- as.matrix(subset(multi, key == "D")[, -c(1,2)])
colnames(big_sphere) <- 1:10
#big_sphere <- rbind(big_sphere,
#                    generate_sphere(1000, 10, 0, 5))

#labels <- c(rep("A", 200), rep("B", 1000))

coords <- basic_tsne(big_sphere, perplexity = 30)
coords$Y <- tourr::center(tourr::rescale(coords$Y))

pl <- ggplot(as.data.frame(coords$Y), aes(V1, V2)) +
  geom_point()
pl

pl +  add_triangles(coords)

sneezy_centroids(big_sphere, coords)

coords2 <- basic_tsne(big_sphere, perplexity = 10)
coords2$Y <- tourr::center(tourr::rescale(coords2$Y))


pl2 <- ggplot(as.data.frame(coords2$Y), aes(V1, V2)) +
  geom_point()
pl2

pl2 +  add_triangles(coords2)


sneezy_centroids(big_sphere, coords2)

```


